# Cloudflare Pages configuration
name = "jacobs-workout-assistant"
compatibility_date = "2024-01-01"
pages_build_output_dir = "dist"

[[d1_databases]]
binding = "DB"
database_name = "workout-db"
database_id = "405a3e9f-dffa-487b-b354-fdf255556bde"
migrations_dir = "d1/migrations"
