#!/usr/bin/env node
/**
 * Project Initialization Script
 * ═══════════════════════════════════════════════════════════════
 * Interactive setup for new projects.
 * Configures tier, modules, and GitHub integration.
 * 
 * Usage: pnpm init:project
 */

import { execSync } from 'child_process';
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';
import { createInterface } from 'readline';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT_DIR = path.resolve(__dirname, '..');

// Colors for terminal output
const colors = {
  reset: '\x1b[0m',
  green: '\x1b[32m',
  yellow: '\x1b[33m',
  red: '\x1b[31m',
  cyan: '\x1b[36m',
  dim: '\x1b[2m',
  bold: '\x1b[1m',
};

function log(message, color = 'reset') {
  console.log(`${colors[color]}${message}${colors.reset}`);
}

function prompt(question) {
  const rl = createInterface({
    input: process.stdin,
    output: process.stdout,
  });

  return new Promise(resolve => {
    rl.question(`${colors.cyan}? ${colors.reset}${question} `, answer => {
      rl.close();
      resolve(answer.trim());
    });
  });
}

async function selectOption(question, options) {
  log(`\n${question}`, 'bold');
  options.forEach((opt, i) => {
    log(`  ${i + 1}. ${opt.label}${opt.description ? ` - ${opt.description}` : ''}`, 'dim');
  });
  
  const answer = await prompt(`Enter choice (1-${options.length}):`);
  const index = parseInt(answer) - 1;
  
  if (index >= 0 && index < options.length) {
    return options[index].value;
  }
  
  return options[0].value; // Default to first option
}

async function main() {
  log('\n═══════════════════════════════════════════════════════════════', 'cyan');
  log('  🚀 Agency Astro Starter - Project Setup', 'cyan');
  log('═══════════════════════════════════════════════════════════════\n', 'cyan');

  // Load current config
  const stackConfigPath = path.join(ROOT_DIR, 'stack.config.js');
  const envPath = path.join(ROOT_DIR, '.env');

  // Project name
  const projectName = await prompt('Project name (kebab-case):') || 'my-project';
  const clientName = await prompt('Client name:') || 'Client';
  const domain = await prompt('Domain (optional, e.g., example.com):') || '';

  // Select tier
  const tier = await selectOption('Select project tier:', [
    { value: 'basic', label: 'Basic', description: 'Astro + Resend (static sites)' },
    { value: 'cms', label: 'CMS', description: 'Astro + Sanity + Resend (content-managed)' },
    { value: 'fullstack', label: 'FullStack', description: 'Astro + Sanity + Supabase + Resend (full apps)' },
  ]);

  // Determine modules based on tier
  const modules = {
    sanity: tier === 'cms' || tier === 'fullstack',
    supabase: tier === 'fullstack',
    resend: true,
    netlify: true,
  };

  log('\n📦 Module Configuration:', 'yellow');
  log(`  • Sanity CMS: ${modules.sanity ? '✅ Enabled' : '❌ Disabled'}`, modules.sanity ? 'green' : 'dim');
  log(`  • Supabase: ${modules.supabase ? '✅ Enabled' : '❌ Disabled'}`, modules.supabase ? 'green' : 'dim');
  log(`  • Resend Email: ✅ Enabled`, 'green');
  log(`  • Netlify: ✅ Enabled`, 'green');

  // GitHub setup
  log('\n🔗 GitHub Configuration:', 'yellow');
  const setupGithub = (await prompt('Set up GitHub integration? (Y/n):'))?.toLowerCase() !== 'n';
  
  let githubUsername = '';
  let githubToken = '';
  
  if (setupGithub) {
    githubUsername = await prompt('GitHub username:');
    githubToken = await prompt('GitHub token (will be saved to .env):');
  }

  // Update stack.config.js
  log('\n⚙️  Updating configuration...', 'yellow');
  
  const newConfig = `/**
 * Stack Configuration
 * ═══════════════════════════════════════════════════════════════
 * Auto-generated by init:project script
 */

export default {
  tier: '${tier}',

  modules: {
    sanity: ${modules.sanity},
    supabase: ${modules.supabase},
    resend: ${modules.resend},
    netlify: ${modules.netlify},
  },

  project: {
    name: '${projectName}',
    client: '${clientName}',
    domain: '${domain}',
    description: 'A modern web application for ${clientName}',
  },

  github: {
    username: '${githubUsername}',
    repoName: '${projectName}',
    isPrivate: true,
  },

  locale: {
    defaultLanguage: 'de-CH',
    supportedLanguages: ['de', 'en', 'fr'],
    formalAddress: true,
  },
};
`;

  fs.writeFileSync(stackConfigPath, newConfig);
  log('  ✅ stack.config.js updated', 'green');

  // Create/update .env
  if (setupGithub && githubToken) {
    let envContent = '';
    
    if (fs.existsSync(envPath)) {
      envContent = fs.readFileSync(envPath, 'utf-8');
    }
    
    // Add GitHub credentials
    if (!envContent.includes('GITHUB_TOKEN')) {
      envContent += `\nGITHUB_TOKEN=${githubToken}`;
    } else {
      envContent = envContent.replace(/GITHUB_TOKEN=.*/, `GITHUB_TOKEN=${githubToken}`);
    }
    
    if (!envContent.includes('GITHUB_USERNAME')) {
      envContent += `\nGITHUB_USERNAME=${githubUsername}`;
    } else {
      envContent = envContent.replace(/GITHUB_USERNAME=.*/, `GITHUB_USERNAME=${githubUsername}`);
    }

    if (!envContent.includes('GITHUB_REPO_NAME')) {
      envContent += `\nGITHUB_REPO_NAME=${projectName}`;
    } else {
      envContent = envContent.replace(/GITHUB_REPO_NAME=.*/, `GITHUB_REPO_NAME=${projectName}`);
    }
    
    fs.writeFileSync(envPath, envContent.trim() + '\n');
    log('  ✅ .env updated with GitHub credentials', 'green');
  }

  // Remove unused module folders
  if (!modules.sanity) {
    const sanityPath = path.join(ROOT_DIR, 'sanity');
    if (fs.existsSync(sanityPath)) {
      log('  🗑️  Removing sanity/ folder (not needed for Basic tier)', 'dim');
      fs.rmSync(sanityPath, { recursive: true, force: true });
    }
  }

  if (!modules.supabase) {
    const supabasePath = path.join(ROOT_DIR, 'supabase');
    if (fs.existsSync(supabasePath)) {
      log('  🗑️  Removing supabase/ folder (not needed for this tier)', 'dim');
      fs.rmSync(supabasePath, { recursive: true, force: true });
    }
  }

  // Run GitHub setup if configured
  if (setupGithub && githubToken && githubUsername) {
    log('\n🔗 Running GitHub setup...', 'yellow');
    try {
      execSync('node scripts/setup-github.js', { cwd: ROOT_DIR, stdio: 'inherit' });
    } catch (error) {
      log('⚠️  GitHub setup had issues. Run "pnpm github:setup" to retry.', 'yellow');
    }
  }

  // Summary
  log('\n═══════════════════════════════════════════════════════════════', 'cyan');
  log('  ✅ Project initialized successfully!', 'green');
  log('═══════════════════════════════════════════════════════════════', 'cyan');
  log('\n📋 Next steps:', 'bold');
  log('  1. Run: pnpm install', 'dim');
  log('  2. Run: pnpm dev', 'dim');
  if (modules.sanity) {
    log('  3. Set up Sanity: Update SANITY_PROJECT_ID in .env', 'dim');
  }
  if (modules.supabase) {
    log('  4. Set up Supabase: Update SUPABASE_URL and keys in .env', 'dim');
  }
  log('  5. Start building! 🚀', 'dim');
  log('');
}

main().catch(error => {
  log(`\n❌ Error: ${error.message}\n`, 'red');
  process.exit(1);
});


